<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Show static about content
 */
class About_Controller extends Template_Controller {

	public $template = 'template';
	public $siteDesc = '';
	protected $siteObj;
	public function __construct(){		
		parent::__construct(); // This must be included	
		$this->siteObj = new Post_Model();
        $this->siteDesc = $this->siteObj->getSiteDescription();
	}
	public function index()
	{
		/*
		 * Show about page
		*/
		$content = new View('about');
		$this->template->title = "About";
		$this->template->description = $this->siteDesc;
		$this->template->content = $content->render();	

	}

	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
	}

} // End Welcome Controller
