<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Used by cron only, to populate the database with content
 */
class Content_Controller extends Template_Controller {

	public function __construct(){
		parent::__construct(); // This must be included
	}

	/*
	 * Use the post model to:
	 * Find new content that I've written on the interwebs
	 */
	public function saveNewPosts(){		
		if (PHP_SAPI === 'cgi-fcgi' || PHP_SAPI === 'cli' || kohana::config('config.name') !== "production"){
			$postObj = new Post_Model;		
			$postObj->searchForNewPosts();
			kohana::log("debug","The function 'saveNewPosts' has run.");
		}else{
			throw new Kohana_User_Exception('Cannot call over the web', 'This is a function that can only be called via the command line.');
		}		
		exit;
	}
	/*
	 * Use the post model to:
	 * Digest it into the database
	 */
	public function digestNewPosts(){
		if (PHP_SAPI === 'cgi-fcgi' || PHP_SAPI === 'cli' || kohana::config('config.name') !== "production"){
			$postObj = new Post_Model;
			$postObj->digestNewPosts();
			kohana::log("debug","The system has digested the posts tabel. HTML is now refreshed.");
		}else{
			throw new Kohana_User_Exception('Cannot call over the web', 'This is a function that can only be called via the command line.');
		}
		exit;
	}

	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call.';
	}

}
