<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Default Kohana controller. This controller should NOT be used in production.
 * It is for demonstration purposes only!
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */
class Welcome_Controller extends Template_Controller {

	// Disable this controller when Kohana is set to production mode.
	// See http://docs.kohanaphp.com/installation/deployment for more details.
	const ALLOW_PRODUCTION = FALSE;

	// Set the name of the template to use
	public $template = 'kohana/template';
	private $db;
	
	public function index()
	{
		/*
		 * Useful snippets
		 * 	$this->template->content->test .= Kohana::debug($xml);
		 *  kohana::log("debug",Kohana::debug($post));	
		 */
		// Load database
		$this->db = new Database('local');
		// Load template
		$this->template->content = new View('welcome_content');
		$postObj = new Post_Model;
		$myDataSources = $postObj->getDataSourceUrls();
		// You can assign anything variable to a view by using standard OOP
		// methods. In my welcome view, the $title variable will be assigned
		// the value I give it here.
		$this->template->title = 'Welcome to Kohana!';

		// An array of links to display. Assiging variables to views is completely
		// asyncronous. Variables can be set in any order, and can be any type
		// of data, including objects.
		$this->template->content->links = array
		(
			'Home Page'     => 'http://kohanaphp.com/',
			'Documentation' => 'http://docs.kohanaphp.com/',
			'Forum'         => 'http://forum.kohanaphp.com/',
			'License'       => 'Kohana License.html',
			'Donate'        => 'http://kohanaphp.com/donate',
			'jQuery'		=> $myDataSources["github"]["jquery"]
		);
		// get some posts as test
		/*$posts = $this->db->select("created_dt")
		->from("kh_posts")
		->get()
		->array_result(true);
		*/
		/* WORKS
		$this->template->content->posts = $this->db->select("*")
		->from("kh_posts")		
		->limit(6,9)
		->orderby("created_dt","desc")
		->get()
		->result_array(true);		
		*/	
		//$this->template->content->posts = $this->db->query("select * from kh_posts group by created_dt order by created_dt desc limit 0,9")->result_array(true);
		$posts = $this->db->query("SELECT posts.type,from_unixtime(posts.created_dt,'%d-%m-%y') as dateKey,posts.content, posts.* FROM (select * from kh_posts) as posts inner join kh_posts as dates on posts.created_dt = dates.created_dt GROUP BY posts.content order by posts.created_dt desc")->result_array(true);
		$this->template->content->posts = array();
		foreach($posts as $key => $value){
			$content = $value->content;
			if($value->teaser !== null){
				$content = $value->teaser;	
			}			
			if(!array_key_exists($value->dateKey,$this->template->content->posts)){
				$this->template->content->posts[$value->dateKey] = array($content);				
			}else{
				$this->template->content->posts[$value->dateKey][] = $content;				
			}	
			
		}
		//$this->template->content->posts = array();
		/*
		$mostRecentPost = $this->db->select("created_dt")
		->from("kh_posts")		
		->limit(1)
		->orderby("created_dt","desc")
		->get()
		->result_array(true);	
		
		
		$this->template->content->posts = array();
		foreach($posts as $post){				
			$this->template->content->posts[] = array(
			"title" => $post->title,
			"content" => $post->content,
			"created_dt" => date("d-m-y",$post->created_dt));
		}
		/**/
		$this->template->content->test = "Oh hai!";
		
	}
	
	public function saveNewPosts(){
		
		$postObj = new Post_Model;		
		$inserts = $postObj->searchForNewPosts();
		echo Kohana::debug($inserts);
		exit;
	}

	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
	}

} // End Welcome Controller